# Generated by Django 3.2.9 on 2021-11-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTO', 'ABERTO'), ('PAGO', 'PAGO'), ('CANCELADO', 'CANCELADO')], default='ABERTO', max_length=10)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_voo', models.IntegerField()),
                ('preco', models.IntegerField()),
                ('data_ida', models.DateField()),
                ('companhia_ida', models.CharField(choices=[('AEROLINEAS', 'AEROLINEAS'), ('AZUL', 'AZUL'), ('COPA AIRLINES', 'COPA AIRLINES'), ('GOL', 'GOL'), ('LATAM', 'LATAM'), ('MAYAIR', 'MAYAIR'), ('PASSAREDO', 'PASSAREDO'), ('SURINAM', 'SURINAM'), ('TAP', 'TAP')], max_length=20)),
                ('data_volta', models.DateField()),
                ('companhia_volta', models.CharField(choices=[('AEROLINEAS', 'AEROLINEAS'), ('AZUL', 'AZUL'), ('COPA AIRLINES', 'COPA AIRLINES'), ('GOL', 'GOL'), ('LATAM', 'LATAM'), ('MAYAIR', 'MAYAIR'), ('PASSAREDO', 'PASSAREDO'), ('SURINAM', 'SURINAM'), ('TAP', 'TAP')], max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('passageiro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clientes', to='passagens.clientes')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='status_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='passagens.status'),
        ),
    ]
